/**
 * GET /api/tracks
 *
 * Reads statically generated track data from a JSON file.
 * The JSON file is generated by `npm run update-tracks` to avoid
 * hitting the Movebank API rate limits on every user request.
 */

import { withErrorHandler } from "@/lib/api-utils";
import seedTracks from "@/data/seed-tracks.json";
import { fetchDynamicObisTracks } from "@/lib/obis";

export const GET = withErrorHandler(async () => {
  let finalTracks = [...seedTracks] as any[];
  
  try {
    // Attempt to fetch fresh OBIS data dynamically
    const dynamicObis = await fetchDynamicObisTracks();
    if (dynamicObis && dynamicObis.length > 0) {
      // Remove stale static OBIS tracks from seed
      finalTracks = finalTracks.filter((t: any) => !t.id.startsWith("obis-"));
      // Append the fresh ones
      finalTracks.push(...dynamicObis);
    }
  } catch (err) {
    console.error("Dynamic OBIS fetch failed, falling back to static seed data", err);
    // On failure, finalTracks just uses the original seedTracks (which includes last known OBIS)
  }

  return Response.json(
    {
      success: true,
      data: finalTracks,
      cachedAt: new Date().toISOString(),
      total: finalTracks.length,
    },
    {
      headers: {
        "Cache-Control": "public, s-maxage=300, stale-while-revalidate=60",
      },
    },
  );
});
