/**
 * GET /api/tracks
 *
 * Reads statically generated track data from a JSON file.
 * The JSON file is generated by `npm run update-tracks` to avoid
 * hitting the Movebank API rate limits on every user request.
 */

import { withErrorHandler } from "@/lib/api-utils";
import seedTracks from "@/data/seed-tracks.json";

export const GET = withErrorHandler(async () => {
  return Response.json(
    {
      success: true,
      data: seedTracks,
      cachedAt: new Date().toISOString(),
      total: seedTracks.length,
    },
    {
      headers: {
        "Cache-Control": "public, s-maxage=300, stale-while-revalidate=60",
      },
    },
  );
});
